# 风云再起抓取 Token 规则
hostname = applet.njqsmx.com

# 这里的 url 后面必须填写你 github 上 fengyun.js 的 Raw 链接
^https:\/\/applet\.njqsmx\.com\/mobile\/business\/sign\/.* url script-request-body https://raw.githubusercontent.com/wenye618/qx/refs/heads/main/js/fengyun.js