# 抓取金桥国际签到数据
^https:\/\/m\.mallcoo\.cn\/api\/user\/User\/CheckinV2 url script-request-body https://raw.githubusercontent.com/wenye618/qx/refs/heads/main/js/jinqiaoguoji.js


hostname = m.mallcoo.cn