# 啦啦宝都抓取 Token 规则
hostname = weixinnew.lalaport-jq.com

# 这里的 url 后面必须填写你 github 上 lalaport.js 的 Raw 链接
^https:\/\/weixinnew\.lalaport-jq\.com:\d+\/api\/Sign\/(SignIn|GetUserSignData) url script-request-header https://raw.githubusercontent.com/wenye618/qx/refs/heads/main/js/lalaport.js
